development:
  adapter: redis
  url: redis://127.0.0.1:6379/1
  channel_prefix: aws_app_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis.xamnwt.ng.0001.use2.cache.amazonaws.com:6379/1
  channel_prefix: aws_app_production